In [29]:
import sys
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plot

In [32]:
img_src = cv.imread('baboon.jpg',1)
cv.imshow(cv.namedWindow('image',cv.WINDOW_NORMAL),img_src)
print(img_src[20,25])

[102 165 156]


In [28]:
rols, cols, chans = img_src.shape
bl, gr, rd = cv.split(img_src)

In [23]:
cv.imshow('Blue',bl)
cv.imshow('Green',gr)
cv.imshow('Red', rd)

In [34]:
ycrcb_image = cv.cvtColor(img_src,cv.COLOR_BGR2YCrCb)
cv.imshow('Y', ycrcb_image)
cv.imshow('Cb', ycrcb_image)
cv.imshow('Cr', ycrcb_image)
print(ycrcb_image[20,25])

[155 129  98]


In [33]:
hsv_image = cv.cvtColor(img_src,cv.COLOR_BGR2HSV)
cv.imshow('Hue', hsv_image)
cv.imshow('Saturation', hsv_image)
cv.imshow('Value', hsv_image)
print(hsv_image[20,25])

[ 34  97 165]
